[project]
name = "rest-api-labs"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-restful>=0.3.10",
    "flasgger>=0.9.7",
    "pymongo>=4.6.0",
    "pydantic-mongo>=2.0.0",
    "pydantic>=2.12.5",
    "httpx>=0.28.1",
    "pytest>=9.0.2",
    "gunicorn>=21.2.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]

[tool.uv.workspace]
members = [
    "library_api",
]
